<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <style>

        /*    Generated by http://www.cssportal.com    */

        #wrapper {
            margin: 0 auto;
            width: 100%;
            background: white;
        }

        #content {
            float: left;
            background: white;
            width: 57%;
            height: 118px;
            border-bottom: 1px solid;
        }

        #leftcolumn {
            background: white;
            width: 18%;
            float: left;
            height: 118px;
            border-bottom: 1px solid;
        }

        #rightcolumn {
            background: white;
            width: 25%;
            float: left;
            height: 118px;
            border-bottom: 1px solid;
        }

        #footer {
            width: 100%;
            background: white;
            clear: both;
            border-bottom: 1px solid;
        }

        #total {
            width: 100%;
            background: white;
            clear: both;
        }

        #assinatura {
            float: left;
            width: 50%;
            background: white;
            clear: both;

        }

        #atendente {
            float: right;
            width: 50%;
            background: white;
            clear: both;

        }

        div#assinatura h5 {
            position: absolute;
            bottom: 0;
        }

        div#atendente h5 {
            position: absolute;
            bottom: 0;
        }



    </style>
</head>
<body>
<div id="wrapper">

    <div id="leftcolumn">
        <img src="{{url("storage/logo/{$company->logo}")}}" width="125px" height="115px">
    </div>
    <div id="content">
        <h3>{{$company->razao_social}}</h3>
        <h5>{{$company->endereco}}</h5>
    </div>
    <div id="rightcolumn">
        <h4>{{$company->telefone}}</h4>
        <h4>{{$company->celular}}</h4>
    </div>
    <div id="footer">
        <h4>
            @if($ordemOrcamento->id_tipo_ordem_servico == 1)
                <b>ORÇAMENTO {{$ordemOrcamento->id}}</b>
            @else
                <b>ORDEM DE SERVIÇO {{$ordemOrcamento->id}}</b>
            @endif
        </h4>
        <h5>{{$ordemOrcamento->created_at->format('d-m-Y | H:i:s')}}</h5>
    </div>

    <div id="footer">
        <h5><b>Cliente:</b> {{$customer->nome}}</h5>
        <h5><b>Endereço:</b> {{$customer->endereco}}</h5>
        <h5><b>CPF/CNPJ:</b> {{$customer->cnpj_cpf}}</h5>
        <h5><b>Telefone:</b> {{$customer->telefone}}</h5>
        <h5><b>Celular:</b> {{$customer->celular}}</h5>
    </div>

    <div id="footer">
        <h5><b>Equipamento:</b> {{$ordemOrcamento->equipamento}}</h5>
        <h5><b>Problema informado:</b> {{$ordemOrcamento->p_info}}</h5>
        <h5><b>Problema constado:</b> {{$ordemOrcamento->p_const}}</h5>
        <h5><b>Serviço executado:</b> {{$ordemOrcamento->s_exec}}</h5>
    </div>

    <div id="footer">
        <h5><b>Técnico responsável: </b>{{$technician->name}}</h5>
        <h5><b>Situação: </b>
            @if($ordemOrcamento->situacao == 1)
                Em aberto
            @elseif($ordemOrcamento->situacao == 2)
                Em andamento
            @elseif($ordemOrcamento->situacao == 3)
                Concluído
            @elseif($ordemOrcamento->situacao == 4)
                Cancelado
            @endif
        </h5>
    </div>


    <div id="footer">
        <div class="table">
            <table class="table">
                <thead>
                <tr>
                    <th>Cód</th>
                    <th>Nome</th>
                    <th>Desconto</th>
                    <th>Valor</th>
                    <th>Quantidade.</th>

                </tr>
                </thead>
                <tbody>
                @foreach($items as $item)
                    <tr>

                        <td>{{$item->id}}</td>
                        <td>{{$item->nome}}</td>
                        <td>{{number_format($item->pivot->desconto, 2, ',', '')}}</td>
                        <td>{{number_format($item->pivot->valor, 2, ',', '')}}</td>
                        <td>{{$item->pivot->qtd}}</td>

                    </tr>
                @endforeach

                </tbody>
            </table>

            <div id="total">
                <h5>Desconto: R$ {{number_format($descontoTotal, 2, ',', '')}}</h5>
                <h3>Total: R$ {{number_format($total - $descontoTotal, 2, ',', '')}}</h3>
            </div>

        </div>
    </div>

    <div id="assinatura">
        <h5><b>Cliente:</b> __________________________________________</h5>
    </div>
    <div id="atendente">
        <h5><b>Atendente :</b>_________________________________________</h5>
    </div>
</div>

</body>
</html>